spring.application.name=logistic-platform-service
server.port=8080
server.servlet.context-path=/logistic-platform-service

# Admin server embedded - points to itself
spring.boot.admin.client.url=${ADMIN_CLIENT_URL:http://localhost:8080/logistic-platform-service}
spring.boot.admin.client.instance.service-base-url=${ADMIN_CLIENT_SERVICE_BASE_URL:http://localhost:8080/logistic-platform-service}
spring.boot.admin.client.instance.management-base-url=${ADMIN_CLIENT_MANAGEMENT_BASE_URL:http://localhost:8080/logistic-platform-service}

# Credentials so the client can register with the secured admin server
# ? Remove these two lines  no credentials needed since actuator is now open
#spring.boot.admin.client.username=${ADMIN_CLIENT_USERNAME:admin}
#spring.boot.admin.client.password=${ADMIN_CLIENT_PASSWORD:admin123}

# Actuator fully open
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

logging.file.name=logs/app.log

# JWT Config
jwt.secret=a-r-q-o-n-QAZ-WSX-975-EDC-642-RFV
jwt.expiration=3600000

spring.datasource.writer.config.platform=postgres
spring.datasource.writer.config.url=jdbc:postgresql://${WRITE_DB_HOST:localhost}:5432/${WRITE_DB_NAME:logistic_db}?currentSchema=${WRITE_DB_SCHEMA:dev}
spring.datasource.writer.config.username=${WRITE_DB_USERNAME:postgres}
spring.datasource.writer.config.password=${WRITE_DB_PW:root}
spring.datasource.writer.config.driverClassName=org.postgresql.Driver
spring.datasource.writer.cp.hikari.idleTimeout=${WRITE_DB_IDLIE_TIMEOUT:20000}
spring.datasource.writer.cp.hikari.maximumPoolSize=${WRITE_DB_MAX_POOL_SIZE:5}
spring.datasource.writer.cp.hikari.minimumIdle=${WRITE_DB_MIN_IDLE:10}
spring.datasource.writer.cp.hikari.poolName=WriteHikariPool
spring.datasource.writer.cp.hikari.connectionTimeout=${WRITE_DB_TIMEOUT:15000}

spring.datasource.reader.config.platform=postgres
spring.datasource.reader.config.url=jdbc:postgresql://${READ_DB_HOST:localhost}:5432/${READ_DB_NAME:logistic_db}?currentSchema=${READ_DB_SCHEMA:dev}
spring.datasource.reader.config.username=${READ_DB_USERNAME:postgres}
spring.datasource.reader.config.password=${READ_DB_PW:root}
spring.datasource.reader.config.driverClassName=org.postgresql.Driver
spring.datasource.reader.cp.hikari.idleTimeout=${READ_DB_IDLE_TIMEOUT:20000}
spring.datasource.reader.cp.hikari.maximumPoolSize=${READ_DB_MAX_POOL_SIZE:5}
spring.datasource.reader.cp.hikari.minimumIdle=${READ_DB_MIN_IDLE:10}
spring.datasource.reader.cp.hikari.poolName=ReadHikariPool
spring.datasource.reader.cp.hikari.connectionTimeout=${READ_DB_TIMEOUT:15000}


#Thread configuration
asyncConfig.corePoolSize=${CORE_POOL_SIZE:15}
asyncConfig.maxPoolSize=${MAX_POOL_SIZE:30}
asyncConfig.queueCapacity=${QUEUE_CAPACITY:100}

app.cors.allowed-origins=${ALLOWED_ORIGINS:http://localhost:5173}

logistic.pod.save.path=${LOGISTIC_POD_SAVE_PATH:/arqon-logistics/uploads/pod}
logistic.pod.get.url=${LOGISTIC_POD_GET_URL:v1/pod-images}
